<?php

namespace LV\ReservationBundle\Repository;

/**
 * commandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends \Doctrine\ORM\EntityRepository
{
    //$ticket->setRateType("enfant");
    function getRateType($advert) 
    {
        
        
    }
}
