<?php

namespace LV\ReservationBundle\Repository;

/**
 * commandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends \Doctrine\ORM\EntityRepository
{
    function getNumberTickets($date) {
        
       $numberTickets = $this->createQueryBuilder('c')
                            ->select('sum(c.numberTickets)')
                            ->where('c.bookingDate = :date')
                            ->setParameter('date', $date)
                            ->getQuery()
                            ->getScalarResult()
                            ;
                            
       $numberTicket = $numberTickets[0][1];
       
       
       return $numberTicket;
       
       
   }
}
