<?php

namespace LV\ReservationBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    function numberTickets($date) {
        
        return $this->createQueryBuilder('t')
                ->select('COUNT(t)')
                ->where('t.date = :date')
                ->setParameter('date', $date)
                ->getQuery()
                ->getSingleScalarResult()
                ;
   }
}
