services:
#    lv_reservation.example:
#        class: LV\ReservationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    
    lv_reservation.sumratetickets:
        class: LV\ReservationBundle\SumRateTickets\LVSumRateTickets