# src/OC/CoreBundle/Resources/config/routing.yml

#oc_core_home:
    #path: /
    #defaults:
        #_controller: LVCoreBundle:Core:index

#oc_core_contact:
    #path: /contact
    #defaults:
       #_controller: LVCoreBundle:Core:contact
